// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.temperature;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.temperature.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentTemperature = 1;</code>
   */
  int getCurrentTemperature();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
