// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.temperature;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.temperature.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 desiredTemperature = 1;</code>
   */
  int getDesiredTemperature();
}
