// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.temperature;

public final class TemperatureControlServiceProto {
  private TemperatureControlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_temperature_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_temperature_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_temperature_TemperatureStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_temperature_TemperatureStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_temperature_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_temperature_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037TemperatureControlService.proto\022\023com.k" +
      "en.temperature\"0\n\022TemperatureRequest\022\032\n\022" +
      "desiredTemperature\030\001 \001(\005\"\032\n\030TemperatureS" +
      "treamRequest\"B\n\023TemperatureResponse\022\032\n\022c" +
      "urrentTemperature\030\001 \001(\005\022\017\n\007success\030\002 \001(\010" +
      "2\364\001\n\031TemperatureControlService\022e\n\016SetTem" +
      "perature\022\'.com.ken.temperature.Temperatu" +
      "reRequest\032(.com.ken.temperature.Temperat" +
      "ureResponse\"\000\022p\n\021StreamTemperature\022-.com" +
      ".ken.temperature.TemperatureStreamReques" +
      "t\032(.com.ken.temperature.TemperatureRespo" +
      "nse\"\0000\001B7\n\023com.ken.temperatureB\036Temperat" +
      "ureControlServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ken_temperature_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ken_temperature_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_temperature_TemperatureRequest_descriptor,
        new java.lang.String[] { "DesiredTemperature", });
    internal_static_com_ken_temperature_TemperatureStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ken_temperature_TemperatureStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_temperature_TemperatureStreamRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_ken_temperature_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ken_temperature_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_temperature_TemperatureResponse_descriptor,
        new java.lang.String[] { "CurrentTemperature", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
