// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.temperature;

public interface TemperatureStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.temperature.TemperatureStreamRequest)
    com.google.protobuf.MessageOrBuilder {
}
