// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.smartthermostart;

public final class SmartThermostatProto {
  private SmartThermostatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_smartthermostart_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_smartthermostart_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_smartthermostart_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_smartthermostart_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037TemperatureControlService.proto\022\030com.k" +
      "en.smartthermostart\"@\n\022TemperatureReques" +
      "t\022\025\n\rthermostat_id\030\001 \001(\t\022\023\n\013temperature\030" +
      "\002 \001(\005\"&\n\023TemperatureResponse\022\017\n\007message\030" +
      "\001 \001(\t2\214\001\n\026SmartThermostatService\022r\n\021Adju" +
      "stTemperature\022,.com.ken.smartthermostart" +
      ".TemperatureRequest\032-.com.ken.smarttherm" +
      "ostart.TemperatureResponse(\001B2\n\030com.ken." +
      "smartthermostartB\024SmartThermostatProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ken_smartthermostart_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ken_smartthermostart_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_smartthermostart_TemperatureRequest_descriptor,
        new java.lang.String[] { "ThermostatId", "Temperature", });
    internal_static_com_ken_smartthermostart_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ken_smartthermostart_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_smartthermostart_TemperatureResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
