// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.smartthermostart;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.smartthermostart.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
