// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureControlService.proto

package com.ken.smartthermostart;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.smartthermostart.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string thermostat_id = 1;</code>
   */
  java.lang.String getThermostatId();
  /**
   * <code>string thermostat_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getThermostatIdBytes();

  /**
   * <code>int32 temperature = 2;</code>
   */
  int getTemperature();
}
