// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package com.ken.light;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.light.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true to turn on, false to turn off
   * </pre>
   *
   * <code>bool on = 1;</code>
   */
  boolean getOn();
}
