// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package com.ken.light;

public interface LightControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.light.LightControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightId = 1;</code>
   */
  java.lang.String getLightId();
  /**
   * <code>string lightId = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightIdBytes();

  /**
   * <code>bool on = 2;</code>
   */
  boolean getOn();
}
