// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package com.ken.light;

public final class LightServiceProto {
  private LightServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_LightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_LightControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_LightControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_LightControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_LightControlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_MotionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_MotionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ken_light_MotionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ken_light_MotionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LightService.proto\022\rcom.ken.light\"\032\n\014L" +
      "ightRequest\022\n\n\002on\030\001 \001(\010\" \n\rLightResponse" +
      "\022\017\n\007success\030\001 \001(\010\"2\n\023LightControlRequest" +
      "\022\017\n\007lightId\030\001 \001(\t\022\n\n\002on\030\002 \001(\010\"I\n\024LightCo" +
      "ntrolResponse\022\017\n\007lightId\030\001 \001(\t\022\017\n\007succes" +
      "s\030\002 \001(\010\022\017\n\007message\030\003 \001(\t\")\n\rMotionReques" +
      "t\022\030\n\020isMotionDetected\030\001 \001(\010\"#\n\016MotionRes" +
      "ponse\022\021\n\tisAlarmOn\030\001 \001(\0102\233\002\n\017LightingSer" +
      "vice\022K\n\014ToggleLights\022\033.com.ken.light.Lig" +
      "htRequest\032\034.com.ken.light.LightResponse\"" +
      "\000\022h\n\027InteractiveLightControl\022\".com.ken.l" +
      "ight.LightControlRequest\032#.com.ken.light" +
      ".LightControlResponse\"\000(\0010\001\022Q\n\014StreamMot" +
      "ion\022\034.com.ken.light.MotionRequest\032\035.com." +
      "ken.light.MotionResponse\"\000(\0010\001B$\n\rcom.ke" +
      "n.lightB\021LightServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ken_light_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ken_light_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_LightRequest_descriptor,
        new java.lang.String[] { "On", });
    internal_static_com_ken_light_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ken_light_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_LightResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_ken_light_LightControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ken_light_LightControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_LightControlRequest_descriptor,
        new java.lang.String[] { "LightId", "On", });
    internal_static_com_ken_light_LightControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ken_light_LightControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_LightControlResponse_descriptor,
        new java.lang.String[] { "LightId", "Success", "Message", });
    internal_static_com_ken_light_MotionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ken_light_MotionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_MotionRequest_descriptor,
        new java.lang.String[] { "IsMotionDetected", });
    internal_static_com_ken_light_MotionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ken_light_MotionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ken_light_MotionResponse_descriptor,
        new java.lang.String[] { "IsAlarmOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
