// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package com.ken.light;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.light.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
