// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package com.ken.light;

public interface LightControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.light.LightControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightId = 1;</code>
   */
  java.lang.String getLightId();
  /**
   * <code>string lightId = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <pre>
   * feedback message
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * feedback message
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
