// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package com.ken.security;

public interface LockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.security.LockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
