// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package com.ken.security;

public interface LockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.security.LockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true to lock, false to unlock
   * </pre>
   *
   * <code>bool lock = 1;</code>
   */
  boolean getLock();
}
