// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package com.ken.security;

public interface SecuritySettingsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ken.security.SecuritySettingsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true to turn on, false to turn off
   * </pre>
   *
   * <code>bool alarmOn = 1;</code>
   */
  boolean getAlarmOn();

  /**
   * <pre>
   * true to lock, false to unlock
   * </pre>
   *
   * <code>bool lock = 2;</code>
   */
  boolean getLock();
}
